version: '2'
services:
  master:
    image: jenkins:latest
    ports:
     - "8080:8080"
     - "50000:50000"
    depends_on:
    - slave_raw
    - slave_nodejs
    - slave_php7

  slave_raw:
    build: 
      context: .
      dockerfile: Dockerfile-slave-raw

  slave_nodejs:
    build: 
      context: .
      dockerfile: Dockerfile-slave-nodejs

  slave_php7:
    build: 
      context: .
      dockerfile: Dockerfile-slave-php7

  test:
    image: ubuntu
