FROM jenkins:latest

# use CLI to install plugins from configs and do some config stuff
# https://github.com/jenkinsci/docker#preinstalling-plugins
# Plus, I need to specify the dependencies of ssh-slaves because it seems that the install-plugins.sh script does not automatically install them (bug?)
# https://github.com/jenkinsci/docker/commit/82272776de574fad2ab0e654a9dcd60df1472d52
RUN /usr/local/bin/install-plugins.sh \
  credentials ssh-credentials ssh-slaves \
  junit script-security \
  javadoc maven-plugin \
  rebuild job-dsl project-inheritance \
  scm-api \
  run-condition structs mapdb-api \
  subversion conditional-buildstep \
  workflow-step-api workflow-scm-step \
  mailer token-macro
RUN /usr/local/bin/install-plugins.sh \
  matrix-project promoted-builds
RUN /usr/local/bin/install-plugins.sh \
  git-client git parameterized-trigger

# indicate that this jenkins is fully configured
# This is not working
# RUN echo 2.0 > /usr/share/jenkins/ref/jenkins.install.UpgradeWizard.state

# copy default jenkins_home content
# https://github.com/jenkinsci/docker#installing-more-tools
COPY jenkins_home/ /usr/share/jenkins/ref/

