FROM mhart/alpine-node:4

COPY slave_core.sh .
RUN chmod +x /slave_core.sh
RUN /slave_core.sh > /dev/null

USER jenkins
RUN touch ~/.sudo_as_admin_successful
WORKDIR /home/jenkins

EXPOSE 22
CMD ["sudo", "/usr/sbin/sshd", "-D"]
